#!/bin/zsh
# install
# Install the bare minimum so process can hand over control to python installer

# Ask what type of installation user wants
read "installOption?What type of installation do you want?
1. Full installation
   (hombrew, terminal, casks, applications, settings, preferences)

2. Clean installation
   (bare minimum: hombrew, terminal)

3. Application installation
   (hombrew, terminal, casks, applications)

4. Preference installation [MUST have all others installed]
   (settings, preferences)
Type [1/2/3/4/other]: "

if [[ "$installOption" = "" || ! "1 2 3 4" =~ "$installOption" ]]; then
    echo Exiting...
    exit
fi

read "askPrompt?Do you want to be prompted about what is being installed [y/n]? "

if [ "$installOption" = "1" ]; then 
    . ./initial/fullInstallation.sh 

elif [ "$installOption" = "2" ]; then
    . ./initial/cleanInstallation.sh

elif [ "$installOption" = "3" ]; then
    . ./initial/applicationInstallation.sh

elif [ "$installOption" = "4" ]; then
    . ./initial/preferenceInstallation.sh

fi

# Restart system
read "response?Press any key to restart computer."
echo "Verification... (ctrl-c to cancel)"
sudo shutdown -r now